version: "3.9"
services:
  web:
    build: .
    image: 8clever/calcio-napoli
    restart: always
    environment: 
      SMTP_URL: smtps://username:password@smtp.example.com/?pool=true
      YOUTUBE_API_KEY: YOUR_API_KEY
    ports: 
      - 3000:3000